<div class="footer-inner">
    <div class="accordion-panel mobile-show">
        <ul class="accordion">
            <li><a class="heading_acc open">Shop</a>
                <div class="footer-shop-list" style="width: 100%; display: block;">
                    <ul>
                        <li><a href="/collections">SHOP BY COLLECTION</a></li>
                        <li><a href="/collections/bracelets">SHOP - BRACELETS</a></li>
                        <li><a href="/collections/necklaces">SHOP - NECKLACES</a></li>
                        <li><a href="/collections/earrings">SHOP - EARRINGS</a></li>
                        <li><a href="/collections/rings">SHOP - RINGS</a></li>
                    </ul>
                </div>
            </li>
            <li><a class="heading_acc">Info &amp; services</a>
                <div class="bg-grey" style="display: none;">
                    <ul>
                        <li><a href="/pages/shipping-returns">SHIPPING &amp; RETURNS</a></li>
                        <li><a href="/pages/contact-us">CONTACT US</a></li>
                        <li><a href="/account">MY ACCOUNT</a></li>
                    </ul>
                </div>
            </li>
            <li><a class="heading_acc">More</a>
                <div class="footer-shop-list" style="width: 100%; display: none;">
                    <ul>
                        <li><a href="/pages/our-story">OUR STORY</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>


</div>
