<div class="header-container">
    <div class="backdrop"></div>
    <div class="header">
        <img class="hamburger-menu" height="25" src="<?php echo $this->getSkinUrl('images/hamburger-menu.svg') ?>">
        <div class="col-3">
            <?php echo $this->getChildHtml('store_language') ?>
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
        <div class="col-3 text-center">
            <?php if ($this->getIsHomePage()):?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php else:?>
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php endif?>
            </div>
            <div class="col-3">
                <?php //echo $this->getChildHtml('topLinks') ?>
                <!-- Cart -->
                

                <div class="account-cart-wrapper">
                    <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account">
                        <span class="account-icon">
                            <img height="28" src="<?php echo $this->getSkinUrl('images/user-icon.svg') ?>" alt=""/>
                        </span>
                    </a>

                    <!-- Cart -->

                    <div class="header-minicart">
                        <?php echo $this->getChildHtml('minicart_head'); ?>
                    </div>
                </div>
            </div>
            <!-- <div class="quick-access">
                <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
                
            </div> -->
            
            <?php echo $this->getChildHtml('topContainer'); ?>
        </div>
        <nav class="main-navigation">
            <div class="menu-close-mobile">×</div>
            <div id="utilities">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
        </nav>
    </div>